### ISSUE TITLE
Picovoice Shepherd bug on Windows-10-AMD64-AMD64 Family 21 Model 112 Stepping 0, AuthenticAMD

### ISSUE THREAD

**Issue by kabilan18** [Picovoice/picovoice#512] opened 2023-03-16 05:40 UTC
The platform does not detect Audio from the STM32F407DISC1 Development board. Instead the application crashes and closes. kindly help with the issue

**Comment by kabilan18** [comment] 2023-03-16 05:42
> The platform does not detect Audio from the STM32F407DISC1 Development board. Instead the application crashes and closes. kindly help with the issue

 \\Listening for  "Picovoice"... 

 keyword file has incorrect format or belongs to a different platform
 loading keyword file #0 failed with 'INVALID_ARGUMENT'
 Picovoice init failed with 'INVALID_ARGUMENT'\\

This is the error we got

**Comment by mrrostam** [comment] 2023-03-16 17:30
I tried reproducing the issue on my end and it seems to be working fine. Once you upload the firmware, there is no valid keyword and context model in it, so the board will start working only after entering your AccessKey and uploading models at the second step.

Based on the log you sent, it seems that `Shepherd` had difficulties uploading the models correctly. Can you please try again and see if you face the same issue constantly? Have you tried other languages as well?

**Comment by mrrostam** [comment] 2023-03-17 17:29
The issue is fixed in the latest version of `pvshepherd` (2.1.2). Can you give it a try and confirm that the issue is resolved for you?

**Comment by mrrostam** [comment] 2023-03-22 23:12
My bad! It seems there was a problem with the packaging! The new released version (`2.1.3`) fixes the issue.

**Comment by kabilan18** [comment] 2023-03-25 04:53
Again after the update the issue arises there is no indication in MIC indicator and CPU indicator it remains the static.
The Dev Board used is STM32F407G-DISC1. Will there be any changes since ST has revised its Board design to the old STM32F407-DISC0
The error i got in cmd is
\\
Exception in Tkinter callback                                                                                           Traceback (most recent call last):                                                                                        File "C:\Users\kabil\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__             return self.func(*args)                                                                                                        ^^^^^^^^^^^^^^^^                                                                                               File "C:\Users\kabil\AppData\Local\Programs\Python\Python311\Lib\site-packages\pvshepherd\shepherd.py", line 849, in _paste_from_clipboard                                                                                                        self._access_key_entry.insert(0, clip.clipboard_get())                                                                                                   ^^^^^^^^^^^^^^^^^^^^                                                                 File "C:\Users\kabil\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 926, in clipboard_get         return self.tk.call(('clipboard', 'get') + self._options(kw))                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                       _tkinter.TclError: CLIPBOARD selection doesn't exist or form "STRING" not defined                                       Exception in Tkinter callback                                                                                           Traceback (most recent call last):                                                                                        File "C:\Users\kabil\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__             return self.func(*args)                                                                                                        ^^^^^^^^^^^^^^^^                                                                                               File "C:\Users\kabil\AppData\Local\Programs\Python\Python311\Lib\site-packages\pvshepherd\shepherd.py", line 1178, in _update_rhino_sensitivity                                                                                                   self.master.send_message("%s %.8f" % (MessageCode.PV_MESSAGE_CODE_RHINO_SENSITIVITY.value[0],                         File "C:\Users\kabil\AppData\Local\Programs\Python\Python311\Lib\site-packages\pvshepherd\shepherd.py", line 1001, in send_message                                                                                                                self._message_thread.send_message(message)                                                                            File "C:\Users\kabil\AppData\Local\Programs\Python\Python311\Lib\site-packages\pvshepherd\shepherd.py", line 1490, in send_message                                                                                                                self._driver.write(text.encode())                                                                                     File "C:\Users\kabil\AppData\Local\Programs\Python\Python311\Lib\site-packages\serial\serialwin32.py", line 325, in write                                                                                                                         raise SerialTimeoutException('Write timeout')                                                                       serial.serialutil.SerialTimeoutException: Write timeout  
//
Again Both the Dev board and  Application Hangs and crashes

**Comment by kabilan18** [comment] 2023-03-25 04:56
> Again after the update the issue arises there is no indication in MIC indicator and CPU indicator it remains the static. The Dev Board used is STM32F407G-DISC1. Will there be any changes since ST has revised its Board design to the old STM32F407-DISC0 The error i got in cmd is \ Exception in Tkinter callback Traceback (most recent call last): File "C:\Users\kabil\AppData\Local\Programs\Python\Python311\Lib\tkinter__init__.py", line 1948, in **call** return self.func(*args) ^^^^^^^^^^^^^^^^ File "C:\Users\kabil\AppData\Local\Programs\Python\Python311\Lib\site-packages\pvshepherd\shepherd.py", line 849, in _paste_from_clipboard self._access_key_entry.insert(0, clip.clipboard_get()) ^^^^^^^^^^^^^^^^^^^^ File "C:\Users\kabil\AppData\Local\Programs\Python\Python311\Lib\tkinter__init__.py", line 926, in clipboard_get return self.tk.call(('clipboard', 'get') + self._options(kw)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ _tkinter.TclError: CLIPBOARD selection doesn't exist or form "STRING" not defined Exception in Tkinter callback Traceback (most recent call last): File "C:\Users\kabil\AppData\Local\Programs\Python\Python311\Lib\tkinter__init__.py", line 1948, in **call** return self.func(*args) ^^^^^^^^^^^^^^^^ File "C:\Users\kabil\AppData\Local\Programs\Python\Python311\Lib\site-packages\pvshepherd\shepherd.py", line 1178, in _update_rhino_sensitivity self.master.send_message("%s %.8f" % (MessageCode.PV_MESSAGE_CODE_RHINO_SENSITIVITY.value[0], File "C:\Users\kabil\AppData\Local\Programs\Python\Python311\Lib\site-packages\pvshepherd\shepherd.py", line 1001, in send_message self._message_thread.send_message(message) File "C:\Users\kabil\AppData\Local\Programs\Python\Python311\Lib\site-packages\pvshepherd\shepherd.py", line 1490, in send_message self._driver.write(text.encode()) File "C:\Users\kabil\AppData\Local\Programs\Python\Python311\Lib\site-packages\serial\serialwin32.py", line 325, in write raise SerialTimeoutException('Write timeout') serial.serialutil.SerialTimeoutException: Write timeout // Again Both the Dev board and Application Hangs and crashes

I have tried all the language models and also tried using audio debugging tool there is no response

**Comment by kabilan18** [comment] 2023-03-25 05:00
> Again after the update the issue arises there is no indication in MIC indicator and CPU indicator it remains the static. The Dev Board used is STM32F407G-DISC1. Will there be any changes since ST has revised its Board design to the old STM32F407-DISC0 The error i got in cmd is \ Exception in Tkinter callback Traceback (most recent call last): File "C:\Users\kabil\AppData\Local\Programs\Python\Python311\Lib\tkinter__init__.py", line 1948, in **call** return self.func(*args) ^^^^^^^^^^^^^^^^ File "C:\Users\kabil\AppData\Local\Programs\Python\Python311\Lib\site-packages\pvshepherd\shepherd.py", line 849, in _paste_from_clipboard self._access_key_entry.insert(0, clip.clipboard_get()) ^^^^^^^^^^^^^^^^^^^^ File "C:\Users\kabil\AppData\Local\Programs\Python\Python311\Lib\tkinter__init__.py", line 926, in clipboard_get return self.tk.call(('clipboard', 'get') + self._options(kw)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ _tkinter.TclError: CLIPBOARD selection doesn't exist or form "STRING" not defined Exception in Tkinter callback Traceback (most recent call last): File "C:\Users\kabil\AppData\Local\Programs\Python\Python311\Lib\tkinter__init__.py", line 1948, in **call** return self.func(*args) ^^^^^^^^^^^^^^^^ File "C:\Users\kabil\AppData\Local\Programs\Python\Python311\Lib\site-packages\pvshepherd\shepherd.py", line 1178, in _update_rhino_sensitivity self.master.send_message("%s %.8f" % (MessageCode.PV_MESSAGE_CODE_RHINO_SENSITIVITY.value[0], File "C:\Users\kabil\AppData\Local\Programs\Python\Python311\Lib\site-packages\pvshepherd\shepherd.py", line 1001, in send_message self._message_thread.send_message(message) File "C:\Users\kabil\AppData\Local\Programs\Python\Python311\Lib\site-packages\pvshepherd\shepherd.py", line 1490, in send_message self._driver.write(text.encode()) File "C:\Users\kabil\AppData\Local\Programs\Python\Python311\Lib\site-packages\serial\serialwin32.py", line 325, in write raise SerialTimeoutException('Write timeout') serial.serialutil.SerialTimeoutException: Write timeout // Again Both the Dev board and Application Hangs and crashes

I have tried all the language models and also tried using audio debugging tool there is no response
Errors:
\\
keyword file has incorrect format or belongs to a different platform
 Picovoice init failed with 'INVALID_ARGUMENT'
\\
AttributeError: 'AudioDebugging' object has no attribute '_language'                                                    Exception in Tkinter callback                                                                                           Traceback (most recent call last):                                                                                        File "C:\Users\kabil\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__             return self.func(*args)                                                                                                        ^^^^^^^^^^^^^^^^                                                                                               File "C:\Users\kabil\AppData\Local\Programs\Python\Python311\Lib\site-packages\pvshepherd\shepherd.py", line 995, in _context_exit                                                                                                                self._show_context_button.state(["!disabled"])                                                                        File "C:\Users\kabil\AppData\Local\Programs\Python\Python311\Lib\tkinter\ttk.py", line 563, in state                      return self.tk.splitlist(str(self.tk.call(self._w, "state", statespec)))                                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                              _tkinter.TclError: invalid command name ".!controlpanel.!button2"                                                       Exception in Tkinter callback                                                                                           Traceback (most recent call last):                                                                                        File "C:\Users\kabil\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__             return self.func(*args)                                                                                                        ^^^^^^^^^^^^^^^^                                                                                               File "C:\Users\kabil\AppData\Local\Programs\Python\Python311\Lib\site-packages\pvshepherd\shepherd.py", line 995, in _context_exit                                                                                                                self._show_context_button.state(["!disabled"])                                                                        File "C:\Users\kabil\AppData\Local\Programs\Python\Python311\Lib\tkinter\ttk.py", line 563, in state                      return self.tk.splitlist(str(self.tk.call(self._w, "state", statespec)))                                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                              _tkinter.TclError: invalid command name ".!controlpanel.!button2"                                                       Exception in Tkinter callback                                                                                           Traceback (most recent call last):                                                                                        File "C:\Users\kabil\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__             return self.func(*args)                                                                                                        ^^^^^^^^^^^^^^^^                                                                                               File "C:\Users\kabil\AppData\Local\Programs\Python\Python311\Lib\site-packages\pvshepherd\shepherd.py", line 995, in _context_exit                                                                                                                self._show_context_button.state(["!disabled"])                                                                        File "C:\Users\kabil\AppData\Local\Programs\Python\Python311\Lib\tkinter\ttk.py", line 563, in state                      return self.tk.splitlist(str(self.tk.call(self._w, "state", statespec)))                                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                              _tkinter.TclError: invalid command name ".!controlpanel.!button2"                                                       Exception in Tkinter callback                                                                                           Traceback (most recent call last):                                                                                        File "C:\Users\kabil\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__             return self.func(*args)                                                                                                        ^^^^^^^^^^^^^^^^                                                                                               File "C:\Users\kabil\AppData\Local\Programs\Python\Python311\Lib\site-packages\pvshepherd\shepherd.py", line 995, in _context_exit                                                                                                                self._show_context_button.state(["!disabled"])                                                                        File "C:\Users\kabil\AppData\Local\Programs\Python\Python311\Lib\tkinter\ttk.py", line 563, in state                      return self.tk.splitlist(str(self.tk.call(self._w, "state", statespec)))                                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                              _tkinter.TclError: invalid command name ".!controlpanel.!button2"

**Comment by mrrostam** [comment] 2023-03-25 15:36
So, just to confirm, are you no longer encountering the error message "keyword file has incorrect format or belongs to a different platform"? The errors displayed in the console indicate that an error has occurred, but it is difficult for me to identify the specific cause of the problem. We have attempted to recreate the issue on various setups, but have not been able to replicate the problem.

**Comment by kabilan18** [comment] 2023-03-26 10:30
I'm encountering same keyword error message in all the platform. when I get the error the application and board starts hanging.

**Comment by mrrostam** [comment] 2023-03-27 15:50
Thank you for sending the logs, but we are still unable to replicate the problem, and everything works as expected for all languages. It's difficult to pinpoint the source of the issue at this point. It's possible that it could be related to hardware, therefore I will be closing this issue but monitoring it in case other users encounter similar difficulties.

By the way, we plan to launch updated versions of Porcupine, Picovoice, and Shepherd soon. It's possible that your issue will be resolved with these new releases, so I suggest keeping an eye on this repository to stay informed.

**Closed by mrrostam** 2023-03-27 15:50 UTC
Labels: bug
