### ISSUE TITLE
Picovoice Console Login Issue

### ISSUE THREAD

**Issue by ShashwatMDas** [Picovoice/picovoice#105] opened 2021-07-18 11:54 UTC
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour
In the picovoice console, after logging in it asks to enter name and  agree to privacy terms. After entering those details and submitting I should be allowed to move forward and train my custom keyword.

### Actual behaviour
![image](https://user-images.githubusercontent.com/43996845/126066001-d31ad692-b3b4-416c-9013-f43117a33d5d.png)
Aftet submitting the details, it doesn't save and shows an error response in one of the network calls in the network tab in dev tools
### Steps to reproduce the behaviour
Create a personal account and then add name.
(Include enough details so that the issue can be reproduced independently.)

**Comment by dbartle** [comment] 2021-07-18 16:46
Sorry you've run into that issue. I'm unable to reproduce the problem on my end. Can you please retry and let me know if the issue re-occurs?

Trying to determine if this was a momentary network issue or an actual bug. Either way, the UI should respond to the error better.

**Comment by ShashwatMDas** [comment] 2021-07-18 17:24
Hi, thanks for the response. I tried again and the same thing is happening with me. I have tried to do it over 3 different network connections as well. Let me know if you need any more information.

**Comment by dbartle** [comment] 2021-07-18 17:28
Can you please email `hello@picovoice.ai` with the email that you used to sign up and reference the URL of this issue? We can investigate the logs and see what's up.

Also, could you please try logging out and logging back in again?

**Comment by ShashwatMDas** [comment] 2021-07-18 17:30
Yes sure, I will mail to them with the specifics. 

I have already tried it after logging out. I even created two accounts with two different email IDs after the first one didn't work. The issue is coming in all the cases for me.

**Comment by dbartle** [comment] 2021-07-26 19:53
We haven't appeared to receive an email from you. Did you send one to `hello@picovoice.ai`? 

If so, can you please try again and comment in this issue, or if not, let us know and we'll close this issue.

**Comment by dbartle** [comment] 2021-07-28 16:37
We haven't heard from you so I'm going to close the issue. Please re-open if you encounter this issue again (and send an email to that address indicating the time that the issue occurred with the email used for the account). We've also added a task internally to make the error message in this scenario appear properly.

**Closed by dbartle** 2021-07-28 16:37 UTC
Labels: bug
