### ISSUE TITLE
Picovoice Console Issue: New wake word "livi" or "lifi" is not recognized

### ISSUE THREAD

**Issue by krembuk** [Picovoice/picovoice#138] opened 2021-09-15 08:51 UTC
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour
The Train Wake Word on console processes the wake word

### Actual behaviour
Missing pronunciations for words: [“lifi”]. If these words are present in a respected English dictionary, please provide a link to the word and its pronunciation via a GitHub issue . Custom pronunciations and branded words can be created for commercial customers; contact Picovoice for more information.

### Steps to reproduce the behaviour
Put "hi livi" or "hi lifi" (expected to be pronounced as hi lee fee) on the wake word training console

**Comment by kenarsa** [comment] 2021-09-15 13:19
This is not a bug. It's a question at this time. Please use the correct label moving forward. These don't see English words and hence we won't be adding them. If I'm wrong provide the link to a dictionary item and I will re-open. If these are company/product names and you are working on a commercial application you can contact the sales team to help out.

**Closed by kenarsa** 2021-09-15 13:19 UTC
Labels: question
