### ISSUE TITLE
Invalid AccessKey in React Native

### ISSUE THREAD

**Issue by marwen22462** [Picovoice/picovoice#500] opened 2023-02-16 14:44 UTC
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Steps to reproduce the behaviour

(Include enough details so that the issue can be reproduced independently.)

**Comment by mrrostam** [comment] 2023-02-16 15:10
@marwen22462 it seems that you forgot to mention the issue you are facing. Without any information, it's impossible for us to help you. I'm gonna close the issue, but feel free to open it again and explain the problem with enough details.

**Comment by marwen22462** [comment] 2023-02-16 18:06
Hello,
I'm using Picovoice  in my react native app and I try to change the woke up
word from "picovoice" to "ok helios" or "OK Google" I create the ppn file
and change the path in the code but when I click start it show me an error
said that the access key must be a valid access key,  and when I change
back the ppn file to Pico voice it work perfectly fine, the same problem
with rhn file

What should I do?

Best regards

**Comment by mrrostam** [comment] 2023-02-16 18:35
The demo is written in a way that if the engine returns `PicovoiceInvalidArgumentError`, it shows [Please make sure your accessKey *** is a valid access key.](https://github.com/Picovoice/picovoice/blob/2ecb24bfe9d5db2d524b975bd60d5dbeb7adf786/demo/react-native/App.tsx#L143), but it doesn't necessarily mean that your AccessKey is invalid.

Based on what you described, I think the problem is how you added the custom models; Can you please refer to the [Custom Wake Words & Contexts](https://picovoice.ai/docs/quick-start/picovoice-react-native/) section in our doc and make sure that you follow all steps correctly?

**Comment by CygnusBell** [comment] 2023-02-20 17:55
I have been trying for days to get the example Web code working with a custom wake word. It works fine with "picovoice" and "porcupine" default words, but I just cannot figure out where to put the PPN, RHN and what files to configure for it. Is there a quick start tutorial available?

I've found guides for React Native and a few other platforms hoping to extrapolate but even though are ambiguous (or more likely I'm lacking understanding) about where to put the files and configure them. Any help would be very much appreciated!

**Comment by mrrostam** [comment] 2023-02-22 19:48
@CygnusBell Have you looked at [`Custom Keywords` in Porcupine Wake Word - Web Quick Start](https://picovoice.ai/docs/quick-start/porcupine-web/)?

**Comment by CygnusBell** [comment] 2023-02-22 19:52
@mrrostam thank you for the reply! Yes, that's the document I'm working off of. I just get lost at the custom part. I'm not sure where to put each of the generated files.

**Comment by mrrostam** [comment] 2023-02-22 20:21
There are two ways for using custom models: copy them to `PublicPath` or convert them to `base64`. The former is shown in detail in the [Web demo](https://github.com/Picovoice/picovoice/tree/master/demo/web) and its [package.json](https://github.com/Picovoice/picovoice/blob/master/demo/web/package.json) file (`ppn-cp` and `rhn-cp`). The latter is explained in [Web Quick Start](https://picovoice.ai/docs/quick-start/picovoice-web/), for which you only need to use `npx pvbase64` (for this cases looking at the [Porcupine web demo](https://github.com/Picovoice/porcupine/blob/master/demo/web/index.html) can also be useful)

**Closed** 2023-02-22 20:24 UTC
Labels: bug
