### ISSUE TITLE
Picovoice Console Issue: 

### ISSUE THREAD

**Issue by FGMarshall** [Picovoice/picovoice#13] opened 2020-12-24 09:31 UTC
Domain-Specific Intent Inference on console.
I am a hobby user and I got all the way to final screen only to find that a download for my Raspberry Pi Rhino would, I think, only stay alive for one month.

To me that is  bug!!!!
Is that true?

Is there a reasonable cost commercial package for home users with one off home control systems?
Few hobby types will bother if their efforts decay after a month.

(ps - It is a fantastic system)

**Comment by kenarsa** [comment] 2020-12-24 23:34
This is not a bug as it is the intended behaviour. That being said we should have done better in terms of documentation. This is fixed in #14. Picovoice will never charge personal users and if you are an individual who is using the software for fun you should stick to personal accounts. 

You can always retrain the same Rhino model using console before the expiry to keep using it indefinitely. You just need to press the train button again!

Is this a hassle? Yes! Is there a plan to improve this? Yes, but not immediately. We are planning to remove this for personal users who are respecting personal terms of use but I can't commit to concrete dates.

**Closed by kenarsa** 2020-12-24 23:34 UTC
Labels: question

**Comment by FGMarshall** [comment] 2020-12-25 16:30
Support
Thanks for the reply.
This is by far the best of the off line systems!

As a lesson 1 Python writer 2 days of learning was invested in a system I found I cannot build up on.
And -
It took a while to see that I need not just use the command line but could find a python program to modify with GPIO etc

Lots of us just copy paste and pray. We built up arduino and Pi - now going very commercial for IOT

> You can always retrain the same Rhino model using console before the expiry to keep using it indefinitely. You just need to press the train button again!

And reload and test a remote raspberry Pi.

Many Thanks

Frank Marshall
