### ISSUE TITLE
Current version on rpi zero: Input Overflowed

### ISSUE THREAD

**Issue by geetee24** [Picovoice/picovoice#98] opened 2021-07-05 05:30 UTC
Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour

no crash
### Actual behaviour
crash once wake word heard after 2 seconds.

s only capture stream
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM input
context:
  expressions:
    turnLights:
      - "[switch, turn] $state:state (all) (the) [light, lights]"
      - "[switch, turn] (all) (the) [light, lights] $state:state"
    changeColor:
      - "[change, set, switch] (all) (the) (light, lights) (color) (to) $color:color"
  slots:
    state:
      - "off"
      - "on"
    color:
      - "blue"
      - "green"
      - "orange"
      - "pink"
      - "purple"
      - "red"
      - "white"
      - "yellow"

[Listening ...]
[wake word]

{
  is_understood : 'true',
  intent : 'turnLights',
  slots : {
    'state' : 'off',
  }
}

Traceback (most recent call last):
  File "/usr/local/bin/picovoice_respeaker_demo", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/pvrespeakerdemo/picovoice_demo.py", line 137, in main
    o.run()
  File "/usr/local/lib/python3.7/dist-packages/pvrespeakerdemo/picovoice_demo.py", line 116, in run
    pcm = audio_stream.read(self._picovoice.frame_length)
  File "/home/pi/.local/lib/python3.7/site-packages/pyaudio.py", line 608, in read
    return pa.read_stream(self._stream, num_frames, exception_on_overflow)
OSError: [Errno -9981] Input overflowed

What is wrong?

### Steps to reproduce the behaviour
standard install
(Include enough details so that the issue can be reproduced independently.)

**Comment by mrrostam** [comment] 2021-07-05 23:16
Are you running anything else on your rpi0? 
I think the cpu cannot handle the overall load, and the audio buffer fills up before pyaudio clears it. ([pyaudio Input overflowed](https://stackoverflow.com/questions/10733903/pyaudio-input-overflowed)

For rpi0 specifically, there is also a [respeaker-rpi0 demo in C ](https://github.com/Picovoice/picovoice/tree/master/demo/respeaker-rpi0) which is more optimized in terms of cpu-usage compared to the python demo. Can you use that for your application?

**Comment by geetee24** [comment] 2021-07-06 02:47
no

**Comment by mrrostam** [comment] 2021-07-06 19:17
I could not reproduce the same behaviour on rpi0, and my understanding is that `pyaudio` encounters some problem when the cpu-usage is high. So I will close this issue.

**Closed by mrrostam** 2021-07-06 19:17 UTC
Labels: bug

**Comment by geetee24** [comment] 2021-07-06 21:15
is totally reproducible.  please reopen

**Comment by mrrostam** [comment] 2021-07-07 13:57
@geetee24 as I mentioned, the root of this issue is `pyaudio` based on the error you got. Are you using the latest version of `pyaudio`?

**Comment by geetee24** [comment] 2021-07-07 14:00
Yes

**Comment by mrrostam** [comment] 2021-07-07 14:14
Can you please give me the versions of `pyaudio`, `pvrespeakerdemo`, `portaudio (libportaudio2 )`, and `Raspbian` that you have on rpi0?
