### ISSUE TITLE
Picovoice Issue:  flutter background service 

### ISSUE THREAD

**Issue by FadiChaalab** [Picovoice/picovoice#82] opened 2021-05-19 14:21 UTC
Am trying to run it in background service but it keeps give me error about missing plugin exception no implementation found for method listen on channel flutter_voice_processor_events.
I need to run it in background service, how to fix this issue?

**Comment by kenarsa** [comment] 2021-05-20 17:16
duplicate of https://github.com/Picovoice/porcupine/issues/421

**Closed by kenarsa** 2021-05-20 17:16 UTC
Labels: question
