### ISSUE TITLE
Picovoice Documentation Issue (/docs/quick-start/picovoice-raspberrypi/)

### ISSUE THREAD

**Issue by tkchang28** [Picovoice/picovoice#17] opened 2021-01-11 08:46 UTC
Hello,

### What is the URL of the doc?
Picovoice Documentation Issue (/docs/quick-start/picovoice-raspberrypi/)

### What's the nature of the issue? (e.g. steps do not work, typos/grammar/spelling, etc., out of date)
I have followed the steps on the documents and cannot seems o bring up the Board with this function.
It prompted the below below..

__________________________________________________________________________________________________________

pi@raspberrypi:~ $ picovoice_demo_mic --keyword_path resources/porcupine/resources/keyword_files/rasberry-pi/porcupine_raspberry-pi.ppn --context_path resources/rhino/resources/contexts/raspberry-pi/smart_lighting_raspberry-pi.rbn
Traceback (most recent call last):
  File "/usr/local/bin/picovoice_demo_mic", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/picovoicedemo/picovoice_demo_mic.py", line 181, in main
    output_path=os.path.expanduser(args.output_path) if args.output_path is not None else None).run()
  File "/usr/local/lib/python3.7/dist-packages/picovoicedemo/picovoice_demo_mic.py", line 48, in __init__
    rhino_sensitivity=rhino_sensitivity)
  File "/usr/local/lib/python3.7/dist-packages/picovoice/picovoice.py", line 71, in __init__
    raise ValueError("Couldn't find Porcupine's keyword file at '%s'." % keyword_path)
ValueError: Couldn't find Porcupine's keyword file at 'resources/porcupine/resources/keyword_files/rasberry-pi/porcupine_raspberry-pi.ppn'.
__________________________________________________________________________________________________________

please help and appreciate for your time...

**Comment by kenarsa** [comment] 2021-01-11 15:37
The error says that the file does not exist. I think you probably cloned the repo without submodules. Please see this: https://github.com/Picovoice/picovoice#demos

If the problem is resolved after please close this issue. Thanks

**Comment by kenarsa** [comment] 2021-01-13 15:34
closing due to inactivity. Please reopen if the issue is not resolved

**Closed by kenarsa** 2021-01-13 15:34 UTC
Labels: documentation
